#
# ディレクトリを作成する Playbook です。
#

---
  - hosts: localhost
    become: yes
    become_method: sudo
    become_user: root
    tasks:

      - name: create hello1 directory
        file: dest=hello1 state=directory owner=root group=root mode=0755


